### ISSUE TITLE
map_chr etc convert character inputs into names

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#115]
e.g.

```R
map_chr(letters, ~ {"1"})
```

**Comment by hadley** [comment]
Not after #118 was fixed :)

**Comment by vspinu** [comment]
Why was this one closed more concretely? 

It'is a very useful feature IMO. I am currently doing either `sapply(x, function(nm)..., simplify=F)` or `set_names(map(x, ..), x)` both of which are awkward.

**Comment by lionel-** [comment]
I think the issue was that it used to be the case, not the other way around. The names of the output should only be set based on the names of the input. This is consistent across all mapping functions. So the canonical way to do it is:

```r
letters %>% set_names() %>% map(some_fun)
```

In addition to consistency, this makes the code and its intent clearer.
