### ISSUE TITLE
map(): data frame in, list out?

### ISSUE THREAD

**Issue by jennybc** [hadley/purrr#153]
When mapping over variables in a data frame, would it be possible to return list, rather than error, if the results don't make a valid data frame? It seems like data-frame-able results would be the exception rather than the rule.

``` r
library(dplyr)
library(purrr)
a <- data_frame(x = rep('a', 3),
                y = c('a', 'b', 'c'),
                z = c(NA, 'b', 'b'))
a %>% 
  map(unique)
#> Error: Variables must be length 1 or 3.
#> Problem variables: z.
```

I can make the above work only by applying `as.list()` before `map()`. (Or by using `lapply()`. But my real example calls for `map_at()` or `map_if()`.)

If I change the input slightly (define `a$z` as `c(NA, 'b', 'z')`), I get something else unexpected because length 1 variables get recycled.

``` r
a <- data_frame(x = rep('a', 3),
                y = c('a', 'b', 'c'),
                z = c(NA, 'b', 'z'))
a %>% 
  map(unique)
#> Source: local data frame [3 x 3]
#> 
#>       x     y     z
#>   (chr) (chr) (chr)
#> 1     a     a    NA
#> 2     a     b     b
#> 3     a     c     z
```

**Comment by lionel-** [comment]
yes the plan for the next version is to make `map()` always return a list. Then we'll have `dmap()` for data frames. It will also handle sliced mapping so that
```r
df <- mtcars %>% slice_rows("cyl")
df %>% dmap(mean)
```
is equivalent to
```r
df %>% by_slice(map, mean, .collate = "rows")
```
Though I'm a bit concerned that the difference between `map_df()` and `dmap()` will be hard to grasp. The former transforms the result to a data frame but won't handle grouping, while the latter does handle grouping. Also, when `.f` returns data frames instead of vectors, `map_df()` will row-bind them but `dmap()` won't.

@hadley Actually the fact that `map_df()` row-binds the results may blur its purpose. When the results are a list of data frames, they are binded together, which I believe is the original intent of that function. But since `bind_rows()` now handles dataframeable objects, it will coerce a named rectangular list to a data frame. In this case it's basically equivalent to our internal function `output_hook()` that currently coerces the results to a df when the input is a df.

Should `map_df()` fail with dataframeable lists to make the difference with `dmap()` clearer?

**Comment by hadley** [comment]
@jennybc this issue should be fixed now

@lionel- yeah, I don't think we have quite the right separation between dplyr and purrr yet. I'll keep thinking about it as I work on the next release of dplyr.
