### ISSUE TITLE
Implement preduce?

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#163]
Parallel reduce would allow you to specific arguments that varied across each call. Would be useful if you want to collapse many joins. Need to think if we could have some convention for naming input elements and matching with arguments.

**Comment by hadley** [comment]
This will require our own C implementation of reduce, and so should will need to wait for #191

**Comment by hadley** [comment]
Note that the presence of init changes how the arguments align:

```R
out <- init
out <- f(out, x[[1]], y[[1]])
out <- f(out, x[[2]], y[[2]])

out <- x[[1]]
out <- f(out, x[[2]], y[[1]])
out <- f(out, x[[3]], y[[2]])
```

To match `pmap()` the call might look like:

```R
preduce(list(dfs, vars), left_join, ...) 
```

but `vars` would have length one less than `dfs` (which makes sense because of fence-posting). Maybe also need `reduce2()`:

```R
reduce2(dfs, vars, left_join, ...)
```

Maybe just start with `reduce2()` and leave `preduce()` for now? Seems harder to imagine use case given `reduce2()`.

**Comment by Ljupch0** [comment]
In terms of use case, I reach for reduce functions when adding cumulatively to an initial object. For instance with the `officer` package you can generate a powerpoint presentation. You start with an empty presentation and every function call adds a slide to the cumulative presentation.  So instead of using pmap that would generate 50 presentations, I've needed a single presentation with 50 slides based on the same template, which sounds like preduce. The `init` is the starting empty template, and then every function call adds a slide. Some pseudo code:

```
preduce <- function(.init, .l, .f, ... ) {
  # smart code
}

preduce(.init = starting_template, .l = data, .f = add_slide) 

#would be
  starting_template %>% 
    add_slide(..1, ..2, ...) %>% 
    add_slide(..1, ..2, ...) %>% 
    add_slide(..1, ..3, ...) %>% ...
```

I have working code of this example here. I needed to iterate a single vector so just `reduce` worked, but a more general `preduce` would be fantastic: https://github.com/Ljupch0/stock_presentations/blob/master/Multiple%20Tickers.RMd

**Comment by moodymudskipper** [comment]
I've been needing this too, the following seems to work fine : 

```
preduce <- function(.l,.f, ..., .init, .dir = c("forward", "backward")) {
  .init = match.arg(.init)
  reduce(transpose(.l), function(x,y) exec(.f, x, !!!y, ...), .init = .init, .dir = .dir)
}
```
