### ISSUE TITLE
flatten_*() and names

### ISSUE THREAD

**Issue by jennybc** [hadley/purrr#165]
Déjà vu! Follow up to "flatten and names" https://github.com/hadley/purrr/issues/157.

`flatten()` now holds  on to names but the typed variants do not.

``` r
library(purrr)

flatten_chr(list(a = "a", b = "b"))
#> [1] "a" "b"

## I expected this
list(a = "a", b = "b") %>% 
{
  set_names(flatten_chr(.), names(.))
}
#>   a   b 
#> "a" "b"
```

**Comment by hadley** [comment]
What would you expect the names to be in this scenario?

```R
flatten_chr(list(a = "a", b = letters))
```

**Comment by hadley** [comment]
This is what the vector flattens are currently designed for:

``` r
library(purrr)
flatten_chr(list(c(a = "a"), c(b = "b")))
#>   a   b 
#> "a" "b"
```

**Comment by jennybc** [comment]
> What would you expect the names to be in this scenario?

```r
flatten_chr(list(a = "a", b = letters))
```

I guess `"a"` then ... this feels a bit like the `tibble::repair_names()` conversation https://github.com/tidyverse/tibble/issues/217. Except this has the added quandary of inner vs outer names.

**Comment by hadley** [comment]
I think I'm going to close this for now - I'm pretty sure the current behaviour makes sense as it always preserves inner names, ignoring outer names. (I don't know if that's useful but it seems much harder to figure out how to use outer names)

**Comment by ilarischeinin** [comment]
I ran into this as I was looking for the most direct way to split the typed `map_*()` functions into two separate steps, regular `map()` and the typing. The manual page for `flatten()` seems to hint this was the right direction:

```r
# You can use flatten in conjunction with map
x %>% map(1L) %>% flatten_int()
# But it's more efficient to use the typed map instead.
x %>% map_int(1L)
```

However, this is what happens with names. `map_dbl()` keeps them whereas `map() %>% flatten_dbl()` doesn't:

```r
library(purrr)

l <- list(a = 1, b = 2, c = 3)

l %>% map_dbl(~ sqrt(.))
#>        a        b        c 
#> 1.000000 1.414214 1.732051 

l %>% map(~ sqrt(.)) %>% flatten_dbl()
#> [1] 1.000000 1.414214 1.732051
```

Of course what I'm trying to do needs an explanation, as the typed variants exist for a reason. 
The motivation here is that I was looking for the best approach to combine `map_*()` with the `future` package, so that I could parallelise the computation. This is at least [one way](https://www.jottr.org/2017/06/05/many-faced-future/#futures-with-purrr-furrr), but it forces one to use `map()` instead of the typed variants.

```r
library(future)

l %>% map(~ sqrt(.) %>% future()) %>% values()
#> $a
#> [1] 1
#> 
#> $b
#> [1] 1.414214
#> 
#> $c
#> [1] 1.732051
```

There are of course multiple options here, like `unlist()` (keeps the names) and `as.numeric()` (drops names). What is was looking for, was the most direct, purrrest, drop-in way, and was hoping `flatten_*()` would hit the spot.

I know the question is complicated, and I'm not suggesting the issue needs to be opened or the current behaviour altered. I just thought I'd mention this point of view, that there would be some value in having a way to do `map()` and the typing in two steps that was as identical as possible to the typed variant.

**Comment by jennybc** [comment]
@ilarischeinin I think your expectation/hope that `map_X()` would be consistent with `map() + flatten_X()` name wise captures what I was thinking when I opened this too. And it is perhaps constructive. In any case, here's a little experiment with inserting a helper function, `eponymize()`, to push names down one level and please the `flatten_*()` functions.

``` r
library(purrr)
library(rlang)

(x <- list(a = "a", b = letters[1:3]))
#> $a
#> [1] "a"
#> 
#> $b
#> [1] "a" "b" "c"
## names -- specifically, *outer* names -- are lost in a flatten
flatten_chr(x)
#> Warning: Outer names are only allowed for unnamed scalar atomic inputs
#>   a             
#> "a" "a" "b" "c"

## push names down one level
eponymize <- function(x) {
  if (is_atomic(x)) {
    set_names(x, rep_along(x, deparse(substitute(x))))
  } else {
    x %>%
      imap(~ set_names(.x, rep_along(.x, .y))) %>% 
      set_names(NULL)
  }
}

a <- letters[1:3]
eponymize(a)
#>   a   a   a 
#> "a" "b" "c"

x %>% 
  eponymize() %>% 
  flatten_chr()
#>   a   b   b   b 
#> "a" "a" "b" "c"

l <- list(a = 1, b = 2, c = 3)
l %>% map_dbl(sqrt)
#>        a        b        c 
#> 1.000000 1.414214 1.732051
l %>% map(sqrt) %>% flatten_dbl()
#>        a        b        c 
#> 1.000000 1.414214 1.732051
l %>% map(sqrt) %>% eponymize() %>% flatten_dbl()
#>        a        b        c 
#> 1.000000 1.414214 1.732051
```

Created on 2018-03-29 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by ilarischeinin** [comment]
Thank you for pointing this out, @jennybc! (And also for the little helper function.)

It seems that this difference between `purrr::flatten_*()` and `rlang::flatten_*()` is actually there on the CRAN versions too:

``` r
library(purrr)                   
                                 
l <- list(a = 1, b = 2, c = 3)   
                                 
l %>% map(sqrt) %>% flatten_dbl()
#> [1] 1.000000 1.414214 1.732051
                                 
library(rlang)                   
#> 
#> Attaching package: 'rlang'
#> The following objects are masked from 'package:purrr':
#> 
#>     %@%, %||%, as_function, flatten, flatten_chr, flatten_dbl,
#>     flatten_int, flatten_lgl, invoke, list_along, modify, prepend,
#>     rep_along, splice
                                 
l %>% map(sqrt) %>% flatten_dbl()
#>        a        b        c 
#> 1.000000 1.414214 1.732051
                                 
packageVersion("purrr")          
#> [1] '0.2.4'
                                 
packageVersion("rlang")          
#> [1] '0.2.0'
```

I wonder if the two packages will converge to one of these two behaviours in the future. Since `rlang`is a maturing package, is it maybe more "cutting-edge" and a sign of things to come? `?rlang::lifecycle` doesn't mention the `flatten*()` functions in any way, so I guess they might be entirely experimental as well.

**Comment by jennybc** [comment]
Yes I think rlang's version will become definitive and purrr will eventually just re-export it.

What I have not researched yet is whether the specific naming behaviour we're looking at was changed intentionally or not.

**Comment by ilarischeinin** [comment]
Just in case someone is searching for purrr+future and ends up on this page:

There is now a dedicated package furrr ([CRAN](https://cran.r-project.org/web/packages/furrr/index.html), [GitHub](https://github.com/DavisVaughan/furrr)) to combine the two. In addition to `future_map()`, it also contains the typed variants like e.g. `future_map_dbl()`. And also the equivalents for `map2()` and `imap()`.
