### ISSUE TITLE
Why do map_if() etc use `c(x)`?

### ISSUE THREAD

**Issue by hadley** [hadley/purrr#169]

**Comment by lionel-** [comment]
I added this when we removed df support from `map()`. The goal is to prevent `[<-` from preserving class.

- This way the conditional variants are consistent with `map()` in that they will always return a list.
- This preserves list semantics and allows `.f` to return any result. Otherwise, `map_if()` with a data frame requires `.f` to return a recyclable vector for example.

On second thought, it should be `unclass()` rather than `c()` since some methods like `c.lazy_dots()` preserve class.

This makes me think that maybe we should have S3 generic versions of map and conditional maps. Then `dmap()`, `dmap_if()` and `dmap_at()` could be df methods of these generics instead of being their own verbs, and other packages could implement their own. Unlike `map()`, the default method for the conditional variants would allow `[<-` to do its thing. And the default main method would do `.x[] <- map(...)`.

`objmap()`, `s3map()`, `smap()`?

**Comment by hadley** [comment]
Hmmm, I think `map_if()` should preserve class since it's implicitly modifying the current object.

Maybe there are effectively two classes of map functions:

1. Functions that preserve the input type (i.e. S3 generics)

1. Functions that use the output type of the function (which since can't be figured out by inspecting the function, needs to be supply in function name or argument value)

I think I now have a good understand of type 1. I'm not so sure about type 2.

**Comment by lionel-** [comment]
We could name (1) type stability and (2) semantical stability.

Since `map_if()` is a variant of `map()` which is a semantically stable function, I would expect it to conform to list semantics.

**Comment by hadley** [comment]
I'm pretty sure `map_if()` should modify in place, so we need to change this behaviour and document the requirements for `.f` more clearly. We may want to consider another name or another variant for the other behaviour.

This has a similar feel to #135

**Comment by lionel-** [comment]
Should we reopen this following our conversation of yesterday?

I think it's now clear that `map()` should be the inplace mapper, and `map_list()` would have list semantics. That ship has sailed though, and `map()` is the one that has list semantics. Since `map_if()` is a variant of `map()` (that would be `map_list_if()` ideally), it should also have list semantics.

**Comment by hadley** [comment]
`map_if()` is now `modify_if()`, which I thought was the conclusion we came to.
