### ISSUE TITLE
Let bindings

### ISSUE THREAD

**Issue by cfhammill** [hadley/purrr#175]
I thought adding let bindings would be a nice addition to cut down on temporary variable assignment 
something like:

```
let <- 
  function(..., expr){
    bindings <- as.list(...)
    with(bindings, expr)
  }
```

It would be nice if there was a way to implement the lisp style &last so the expression would be bound implicitly. Although it wouldn't show up in the function signature, we could do:

```
let <- 
  function(...){
    arg_list <- as.list(...)
    with(arg_list[1:(length(arg_list) - 1)], 
         tail(arg_list, 1))
    }
```

Any thoughts?

**Comment by smbache** [comment]
Is this not essentially what magrittr's `%$%` does?

```R
iris %>% cor(Sepal.Length, Sepal.Width)
```

It essentially works as the pipe operator but wrapping the rhs in a `with` statement.

**Comment by smbache** [comment]
Well not exactly, of course...

**Comment by cfhammill** [comment]
Yes the %$% operator serves the same purpose, I actually didn't know it existed. There may still be a use-case for having a named pre-fix version, but maybe it's not necessary.

**Comment by lionel-** [comment]
Strictly speaking, a `let` construct would not fit well in purrr because we try to avoid using `...` except for additional arguments to `.f`. But we could provide a `let-alist` variant. Compared to `%$%`, it would work without non-standard evaluation and would be composable.

```{r}
all_named <- function(x) {
  n <- names(x)

  if (is.null(n)) {
    return(FALSE)
  }

  if (any(n == "")) {
    return(FALSE)
  }

  if (length(unique(n)) != length(n)) {
    return(FALSE)
  }

  TRUE
}

using <- function(..x, ..f, ...) {
  if (!all_named(..x)) {
    stop("..x must be named", call. = FALSE)
  }

  closure_env <- new.env(parent = environment(..f))
  walk2(names(..x), ..x, assign, closure_env)
  environment(..f) <- closure_env

  ..f(...)
}
```

Then:

```{r}
foo <- function() {
  sum(cyl * disp)
}

using(mtcars, foo)
#> [1] 51872.4
```

It won't work with functions making special assumptions about where to find variables (here, the calling env or the env recorded by `~`):
```{r}
using(mtcars, lm, disp ~ cyl)
#> Error in eval(expr, envir, enclos): object 'disp' not found
```

But it is composable:
```{r}
invoke(using, ..x = mtcars, ..f = foo)
#> [1] 51872.4
```

Maybe we could also provide a function operator version:
```{r}
invoke(bind(mtcars, foo))
```

**Comment by smbache** [comment]
Re: `%$%` and non-standard eval: the "simplified" branch has support for using formulas:

```R
iris %$% ~cor(Sepal.Length, Sepal.Width)

# also with usual pipe, for using dots:
letters %>% ~gsub("[a-k]", "z", .)
```

re composable: sure, that's a point.

**Comment by cfhammill** [comment]
@lionel- I like the using moniker, it fits the purrr philosophy at lot better than let, and a little less clunky sounding than letting. 

I think you can replace the walk2 code with list2env(..x, closure_env) then you no longer need the name checking code. I also really like the bind idea, I can see my self using both `using` and `bind`.

**Comment by lionel-** [comment]
Thanks for the `list2env()` idea. However it'll assign duplicated names twice (overwriting the second time) instead of failing so it's still better to check the names manually.

Let's see what Hadley thinks. If you have some compelling use cases for these functions I'd love to see them :). I pondered writing a let function for purrr before but I thought that passing values by separate arguments or in a list is preferable to binding variables in the closure env. And for interactive applications or scripts (as opposed to programming reusable functions) we have `with()` and `%$%`.

**Comment by hadley** [comment]
I'd like to see a few use cases - I don't generally see temporary variable creation to be a problem, and we already have `local()`.

(BTW @lionel- you also need to check for `NA` names)

**Comment by lionel-** [comment]
One area where this may be useful is overwriting functions in unit tests.

Often the functions you want to test are impure and rely on some state. For example the tested function might call `project_files()` to get the filenames currently used in a project. It'd be useful to easily overwrite such stateful functions so that they always return the same thing:

```r
project_files <- function() {
  stopifnot(wd_is_project())
  ls()
}

bindings <- list(project_files = function() c("file_a", "file_b"))

feature <- function() {
  files <- project_files()
  toupper(files)
}

using(bindings, feature)
#> [1] "FILE_A" "FILE_B"
```


It should also be possible to simulate a dynamic rebinding by recursing over all calls in the function body. This would handle the case where the stateful functions are called deeper than `f`. This is going to be much more tricky though, because we'll have to:

- check for usage of flagged functions and objects
- rebind the relevant functions (clone them with a new parent env containing the new bindings)
- rebind these rebinded functions in the parent env of the calling function and so on until we reach `f`.

So that would involve quite a bit of bookeeping and rebinding to get the scoping right. And this is probably going to be quite fragile with NSE functions that make assumptions about parent and/or calling environments.

In any case, the static rebinding should already be useful for unit tests.

**Comment by hadley** [comment]
This feels out of scope for purrr to me.
