### ISSUE TITLE
map and lazy evaluation

### ISSUE THREAD

**Issue by mplourde** [hadley/purrr#191]
``` r
library(purrr)
packageVersion('purrr')
# [1] '0.2.1.9000'
```

This is an issue I encountered with newer releases of **purrr** when using `map` to wrap functions. `map` in prior versions of **purrr** didn't have this issue, but I'm not sure when the change occurred. Consider the following example where I create a list of functions and then wrap them with `lapply`:

``` r
funs <- list(
    function() message('fun1'),
    function() message('fun2'),
    function() message('fun3')
)

wrapper <- function(fun) {
    function() fun()
}

. <- funs %>%
    lapply(wrap_fun) %>% 
    invoke_map()
# fun1
# fun2
# fun3
```

When I perform this task with `map`:

``` r
. <- funs %>% 
    map(wrapper) %>%
    invoke_map()
# fun3
# fun3
# fun3
```

`force`ing the `fun` argument of `wrapper` fixes the issue:

``` r
forced_wrapper <- function(fun) {
    force(fun)
    function() fun()
}

. <- funs %>% 
    map(forced_wrapper) %>%
    invoke_map()
# fun1
# fun2
# fun3
```

Since `map` basically supplants `lapply`, it would be helpful if they behaved the same in this respect.

**Comment by zhiyuanshi** [comment]
First of all, thanks @hadley for writing such wonderful package. I second this issue and can provide another (simpler) example.

Very often I want to make a list of functions that depends on some varying parameters. For example, making a list of functions that print `1..5`.

```r
> f <- map(1:5, function(i) function() print(i))
```

However, if I try to call the first one, it gives `5` instead of `1`. This contradicts to my intuition with functional programming and more specifically lexical scoping, and for the unaware, can lead to serious bugs in code.

```r
> f[[1]]()
[1] 5
```

With a bit of searching, I found one workaround is to make another factory function and explicitly reference `i` in its body, such as:

```r
> make_f <- function(i) { i; function() print(i) }
> f <- map(1:5, make_f)
> f[[1]]()
[1] 1
```

But I think we don't have the issue with `lapply`:

```
> f <- lapply(1:5, function(i) function() { print(i) })
> f[[1]]()
[1] 1
```

**Comment by hadley** [comment]
This is a consequence of R's delayed evaluation - however `lapply()` somehow works around it so we should too.

**Comment by jimhester** [comment]
For reference the R-devel thread where this was changed in lapply is https://stat.ethz.ch/pipermail/r-devel/2015-February/070686.html

**Comment by hadley** [comment]
Implemented in https://github.com/wch/r-source/commit/14f904c32a44010d4dfb8a829805648a88c22f53
