### ISSUE TITLE
map_at() and map_if() convert data frame (or tbl_df) to plain list

### ISSUE THREAD

**Issue by jennybc** [hadley/purrr#192]
This seems to be new, as it has broken some things for me. And yet I see "list" as the return value, so maybe it's intentional? But I don't think it was always this way.

Just run any of the examples from the `conditional-map` help file to see what i mean.

Here is one such example. Note that iris is converted from data frame to list.

``` r
library(purrr)
str(iris)
#> 'data.frame':    150 obs. of  5 variables:
#>  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
#>  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
#>  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
#>  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
#>  $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
iris %>%
  map_if(is.factor, as.character) %>%
  str()
#> List of 5
#>  $ Sepal.Length: num [1:150] 5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
#>  $ Sepal.Width : num [1:150] 3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
#>  $ Petal.Length: num [1:150] 1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
#>  $ Petal.Width : num [1:150] 0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
#>  $ Species     : chr [1:150] "setosa" "setosa" "setosa" "setosa" ...
```

**Comment by jennybc** [comment]
It happened here, which isn't that surprising: 1ea155b49007e1f0e5d5ba596c369c1bafcff45f. Is it intentional that use of conditional mapping converts data frame to list?

**Comment by jennybc** [comment]
OK I am now using `dmap_at()` and `dmap_if()` successfully! Maybe the docs for `map_if()` and `map_at()` shouldn't feature data frames so heavily and should mention/link to `dmap_at()` and `dmap_if()` for data frame input?

**Comment by lionel-** [comment]
> Is it intentional that use of conditional mapping converts data frame to list?

Yes I did that commit so that conditional mapping would be consistent with usual mapping: always return a list, and `.f` can return vectors of any length rather than one of `c(1, nrow(.x))`. This is being discussed here: #169

> Maybe the docs for map_if() and map_at() shouldn't feature data frames so heavily

Indeed. Depends on what we decide in issue 169. I think we need the `map()` family to be about list behaviour, and a more general mapping family that dispatches on class, let's say `s3map()`. We could first dispatch a first time on `s3map()` so that completely specific methods can be written (such as for data frames where we allow grouped mapping). And then a second level of dispatch in `s3map.default()` where we make use of subset-assign generics. `lapply()` in base R will soon dispatch on `[[<-` as well.
