### ISSUE TITLE
export magrittr::extract()?

### ISSUE THREAD

**Issue by jennybc** [hadley/purrr#223]
I taught `purrr` today. We selected multiple elements at the same level of the list hierarchy. Overall reaction was "elegant and simplifying", but mapping `[` was described as "ugly and horrifying".

Is there any chance of re-exporting `magrittr::extract()`?

``` r
library(purrr)
library(magrittr)

x <- list(list(one = list(alpha = 1, beta = 2), two = "three", three = 4),
          list(one = list(alpha = 5, beta = 6), two = "seven", three = 8))
#x %>% map_dbl(c("one", "beta"))
#x %>% map_df(`[`, c("two", "three"))
x %>% map_df(extract, c("two", "three"))
#> # A tibble: 2 x 2
#>     two three
#>   <chr> <dbl>
#> 1 three     4
#> 2 seven     8
```

**Comment by lionel-** [comment]
> mapping [ was described as "ugly and horrifying"

:) That may just be because they are not used to it. Once you get the hang of mapping operators you can do stuff like this: ``x %>% some(`==`, "")`` which is kind of elegant I would say.

`extract()` is already quite overloaded across packages. Maybe `vct_subset()` and `vct_extract()` for `[`and `[[` respectively? I like the `vct_` prefix (or maybe `vec_`) but it requires knowing that both lists and atomic vectors are vectors and it's not how R neophytes usually think about it.

**Comment by jennybc** [comment]
> That may just be because they are not used to it

That's true. My own horror at this has now faded to a distant memory.

I think it catches attention because many people don't predict that using a vector as `.f` will index at successively deeper levels of the input, e.g. `map_dbl(c("one", "beta"))` in the example. That's not very well-known. So it's easy to be surprised about which syntax does what. And to be disappointed about which one requires a bit more work.

`retrieve()`?

Also in a past email conversation, there was talk of a select method for lists. Reminding you of a relevant example you wrote:

``` r
library(purrr)
library(dplyr)
x <- rerun(2, head(mtcars,2))
x %>% map_df(select, cyl, am)
#>   cyl am
#> 1   6  1
#> 2   6  1
#> 3   6  1
#> 4   6  1
```

**Comment by hadley** [comment]
I'd rather fix this by improving the documentation for `map()` so that you know you can use a character vector to index deeply into an object.

**Comment by jennybc** [comment]
I never really thought this would fly but just want to point out this issue was about retrieving "multiple elements at the same level of the list hierarchy". So, more like `dplyr::select()` but for lists. It was explicitly NOT about using "a character vector to index deeply into an object", which is already well documented.

**Comment by hadley** [comment]
Oh gotcha. I think an explicit `[` is probably still the best way to do that even if it makes your students retch in horror.

**Comment by dmi3kno** [comment]
The issue with explicit `[`, as indicated [here ](https://community.rstudio.com/t/multi-value-purrr-pluck/2313/6) and [here](https://stackoverflow.com/questions/46983716/does-a-multi-value-purrrpluck-exist) is that it does not have crucial `.default`/`.null` handling. I would insist that the issue is still open and there's a need for multi-value `pluck` for "tidying" lists.

**Comment by batpigandme** [comment]
@dmi3kno since this issue was closed over a year ago, commenting here is pretty low-visibility. If you could please open a new issue that refers back to this with your reprex etc., it will be much easier for the maintainers to find it.

Thanks
