### ISSUE TITLE
Undefined `.y` in example for `accumulate`

### ISSUE THREAD

**Issue by metanoid** [hadley/purrr#277]
In the documentation for `accumulate` we have
```
library(dplyr)  
library(ggplot2)  
rerun(5, rnorm(100)) %>%  
set_names(paste0("sim", 1:5)) %>%  
map(~ accumulate(., ~ .05 + .x + .y))
```

Maybe I'm missing something obvious, but it's not at all clear to me what `.y` is, in this context.  `map` is running accumulate on each list element independently, so `.x` should be the list element data.  What is `.y`?

**Comment by dandermotj** [comment]
This is not well documented in `purrr` and I had a similar issue in understanding this in the past, but it's actually quite simple. As the accumulate function applies `.f` to the list `.x` it outputs a value for each element of the list. This value is `.x` and can be used in `.f`. `.y` is the value on the list which `.f` applies to. 

That's kind of confusing to read so just look at this example below. I'm going to take the vector `1:10` and `accumulate` along it with a function `.f` which just outputs its input. 
```r
1:10 %>% accumulate(~ .y)
 [1]  1  2  3  4  5  6  7  8  9 10
```
This is the equivalent of `map`. Now let's look at what happens if we put `.x` in place of `.y` - `.f` is going to take as its input the value it previously outputted.
```r
1:10 %>% accumulate(~ .x)
[1] 1 1 1 1 1 1 1 1 1 1
```
So what is happening here is that the first value of 1:10 is 1. `.f` takes 1, and outputs 1. And then it moves onto 2 in the list, but `.f` takes 1 again, (because that's what it previously outputted) and outputs 1. We are recursively applying the function here.

Another really quick example, just adding 1:
```r
c(100, 1:9) %>% accumulate(~ 1 + .y)
[1] 100   2   3   4   5   6   7   8   9  10
c(100, 1:9) %>% accumulate(~ 1 + .x)
```

If you are at all familiar with basic time series, you can think of the `accumulate` as a way to express an [AR(1) process](https://en.wikipedia.org/wiki/Autoregressive_model) - which what the example models:

```r
# First Order Autoregressive Process with rho = 0.5
rnorm(100) %>% accumulate(.y + 0.5*.x)
```

**Comment by metanoid** [comment]
Great explanation, thanks! That's a nice design, actually. Maybe this
explanation is listed somewhere in the purrr vignette, but I missed it. If
it's not there, I think it should be.
