### ISSUE TITLE
map2 and map3 fail with vector as additional argument

### ISSUE THREAD

**Issue by steromano** [hadley/purrr#54]
E.g.
```
f <- function(x, y, zs) x + y + mean(zs)
map2(1:2, 1:2, f, zs = 1) # works
map2(1:2, 1:2, f, zs = 1:2) # wrong result: vectorizes over zs too
map2(1:2, 1:2, f, zs = 1:3) # Error: all(lengths %in% c(1, n)) is not TRUE
```

**Comment by lionel-** [comment]
One quick way to fix this is by encapsulating the dots in an additional list in `map_n()`:

```r
map_n <- function(.l, .f, ...) {
  args <- recycle_args(c(.l, list(list(...))))
  do.call("Map", c(list(quote(.f)), args))
}
```

But this is not very efficient since it creates a new list of same length as `.x` with copies of the additional arguments.

So another way is to fill out the additional arguments with `partial()`:

```r
map_n <- function(.l, .f, ...) {
  f <- do.call(partial, list(`_f` = quote(.f), ...))
  args <- recycle_args(.l)
  do.call("Map", c(list(quote(f)), args))
}
```

This way `.f` is turned into this function:
```r
function (...) .f(zs = 1:2, ...)
```

But I wonder if we should have a version of `partial()`, or an argument, so that the dots come first in the signature. I could see this creating some problems for position matching of arguments.

**Comment by lionel-** [comment]
Fixed once #55 is merged.

**Comment by sumprain** [comment]
Another way to fix this will be to use `mapply`, instead of `Map` function as follows

```
map_n <- function(.l, .f, ...) {
  args <- recycle_args(.l)
  do.call("mapply", c(list(quote(.f)), args, MoreArgs = quote(list(...)), SIMPLIFY = FALSE))
}
```

`mapply` has `MoreArgs` argument, which takes on additional arguments given as ...

Bye

**Comment by sumprain** [comment]
I have added a PR for the same #59.
